version: 1.0.{build}
build_script:
- cmd: >-
    cd C:\projects\organizeschoolwork

    py -3.6 -m pip install cx_freeze python-docx

    py -3.6  templater.py

    py -3.6 setup.py bdist_msi
test: off
artifacts:
- path: dist\OrganizeSchoolWork.exe
  name: OrganizeSchoolWork.exe
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))